# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "44e37553a294054ac8294f8779a36a3a"
application_url = "https://surely-assessed-bite-pin.trycloudflare.com"
embedded = true
name = "fcdtc-fynd"
handle = "fcdtc-fynd"

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://surely-assessed-bite-pin.trycloudflare.com/auth/callback",
  "https://surely-assessed-bite-pin.trycloudflare.com/auth/shopify/callback",
  "https://surely-assessed-bite-pin.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "app-widget-import.myshopify.com"
automatically_update_urls_on_dev = true
